services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Waits for PostgreSQL to be ready

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: timemanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d timemanager_db"]
      interval: 5s
      retries: 5
      start_period: 10s # Allow some time for DB to start

volumes:
  postgres_data:
