services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react-native-frontend
    ports:
      - "8081:8081"
      - "19000:19000" # Expo app communication
      - "19001:19001" # Expo push notifications
      - "19002:19002" # Web interface to view the QR code
    volumes:
      - ./frontend:/app
    command: npm start
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: timemanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
