# Generated by Django 5.1.3 on 2025-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='synced',
            field=models.BooleanField(default=True),
        ),
    ]
