# Generated by Django 5.1.3 on 2024-12-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('activity', 'Activity'), ('project', 'Project')], max_length=20)),
                ('color_preset', models.CharField(default='green', max_length=50)),
                ('productive', models.BooleanField(default=True)),
                ('lap_name', models.CharField(default='Lap', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tags.tag')),
            ],
        ),
    ]
