# Generated by Django 5.1.3 on 2024-12-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
    ]
