# Generated by Django 5.1.3 on 2025-02-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tagindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagIndex',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='type',
            new_name='module_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tag',
            name='children',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color_preset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='lap_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
