# Generated by Django 5.1.3 on 2025-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_delete_tagindex_rename_type_tag_module_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
