# Generated by Django 5.1.3 on 2025-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
