# Generated by Django 5.1.3 on 2025-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_id', models.IntegerField()),
                ('total_work_time', models.IntegerField(default=0)),
                ('total_break_time', models.IntegerField(default=0)),
                ('intervals', models.JSONField(default=list)),
                ('laps', models.JSONField(default=list)),
            ],
        ),
    ]
