# Generated by Django 5.1.3 on 2025-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.BigIntegerField(null=True),
        ),
    ]
