# Generated by Django 5.1.3 on 2025-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sessions', '0002_session_end_time_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
