/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/authScreen`; params?: Router.UnknownInputParams; } | { pathname: `/authSelection`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workplace` | `/workplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles/tasksStyles` | `/styles/tasksStyles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles/watchStyles` | `/styles/watchStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/addStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/authSelectionStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/loginStyles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add`; params?: Router.UnknownOutputParams; } | { pathname: `/authScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/authSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workplace` | `/workplace`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/styles/tasksStyles` | `/styles/tasksStyles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/styles/watchStyles` | `/styles/watchStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/addStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/authSelectionStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/loginStyles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add${`?${string}` | `#${string}` | ''}` | `/authScreen${`?${string}` | `#${string}` | ''}` | `/authSelection${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watch${`?${string}` | `#${string}` | ''}` | `/watch${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workplace${`?${string}` | `#${string}` | ''}` | `/workplace${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/styles/tasksStyles${`?${string}` | `#${string}` | ''}` | `/styles/tasksStyles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/styles/watchStyles${`?${string}` | `#${string}` | ''}` | `/styles/watchStyles${`?${string}` | `#${string}` | ''}` | `/styles/addStyles${`?${string}` | `#${string}` | ''}` | `/styles/authSelectionStyles${`?${string}` | `#${string}` | ''}` | `/styles/loginStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/authScreen`; params?: Router.UnknownInputParams; } | { pathname: `/authSelection`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workplace` | `/workplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles/tasksStyles` | `/styles/tasksStyles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/styles/watchStyles` | `/styles/watchStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/addStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/authSelectionStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/loginStyles`; params?: Router.UnknownInputParams; };
    }
  }
}
